# Target Dataset
# TENNIS
target_dataset: TENNIS
target_data_dir: /mnt/ssd2/lingyu/Tennis/data/TENNIS/
# Few-shot evaluation JSON (使用 train.json 作为评估数据，包含标签)
fewshot_eval_json_path: /mnt/ssd2/lingyu/Tennis/train.json
# Unlabel JSON (用于训练，无标签)
unlabel_json_path: /mnt/ssd2/lingyu/Tennis/unlabel.json
target_sampling_rate: 1
target_json_path: /mnt/ssd2/lingyu/Tennis/train.json

# add
source_sampling_rate: 1