# Modality specific parameters
# FLOW
mode: flow
patch_size: [16, 16]
input_size: [224, 384]
# mean: [0.0507, 0.4671] 论文中的设置
# std: [10.9280, 8.6857] 论文中的设置
mean: [0.251604, 0.032037] # 采样1000个flow数据计算得到的均值
std: [6.777361, 3.229428] # 采样1000个flow数据计算得到的均值
