defaults:
  - _self_
  - modality: skeleton  # skeleton mode
  - dataset: tennis  # epic, meccano, wear

# Augmentation parameters
color_jitter: 0.0
train_interpolation: bicubic

target_json_path: /mnt/ssd2/lingyu/Tennis/train.json
unlabel_json_path: /mnt/ssd2/lingyu/Tennis/unlabel.json
target_data_dir: /mnt/ssd2/lingyu/Tennis/data/TENNIS/

# Skeleton data directory
skeleton_dir: /mnt/ssd2/lingyu/Tennis/data/TENNIS/skeletons/f3set-tennis

# Dataset params
num_frames: 16
mask_type: tube # ['random', 'tube']
mask_ratio: 0.9

# Source Dataset (not used in unlabel-only mode)
# Ego4D
source_data_dir: /data/ego4d_data/v1
source_json_path: cdfsl/source/ego4d/annotations/ego4d_train.json  # 相对路径，相对于项目根目录

# add
source_sampling_rate: 1
