hydra:
  run:
    dir: ./output/${now:%Y-%m-%d}/${now:%H-%M-%S}/mmdistill_tennis

defaults:
  - _self_
  - trainer: mm_distill_trainer_tennis
  - data_module: mm_distill_data_module_tennis

seed: 42
monitored_metric: loss
dirpath: checkpoints/
train: True
test: False
accelerator: gpu
devices: [0]
strategy: deepspeed
ckpt_path:

batch_size: 4
num_workers: 2
